name: Lighthouse CI

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:4321
            http://localhost:4321/blog
            http://localhost:4321/about
            http://localhost:4321/contact
          budgetPath: ./lighthouse-budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('.lighthouseci/manifest.json', 'utf8'));

            let comment = '## 🔦 Lighthouse CI Results\n\n';
            comment += '### Performance Scores\n\n';
            comment += '| Page | Performance | Accessibility | Best Practices | SEO |\n';
            comment += '|------|-------------|---------------|----------------|-----|\n';

            results.forEach(result => {
              const url = result.url.replace('http://localhost:4321', '');
              const scores = result.summary;
              comment += `| ${url || '/'} | ${scores.performance * 100} | ${scores.accessibility * 100} | ${scores['best-practices'] * 100} | ${scores.seo * 100} |\n`;
            });

            comment += '\n[View full report](' + results[0].reportUrl + ')';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
